### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by hron84** [cornet/ccze#1]
The link in the README (http://bonehunter.rulez.org/CCZE.html) does not point to the manual of this software anymore.

**Comment by hron84** [comment]
@cornet why did you closed this issue? links in the README file still not point to the documentation of this software.

**Comment by cornet** [comment]
Sorry @hron84, must have forgot to post a reply before closing.

Please see https://github.com/madhouse/ccze  which is the upstream version of ccze. I'm not the maintainer, just someone that pulled the repo into github a number of years ago :) Apologies for the confusion.

**Comment by hron84** [comment]
@cornet I see. This repo is not a normal fork (and does not mention the upstream repo), that caused me a confusion. Could you please update the description of the repository, to clarify this fact to later visitors?
