### ISSUE TITLE
slowness

### ISSUE THREAD

**Issue by bingalls** [cornet/ccze#3]
ccze works here, but why is the following case slow? Perhaps _best practices_ on wiki docs would help?
For a 1M log: (way too slow on larger logs)
  `time cat my.log | ccze | less -rp error`    #4.3 seconds
  `time cat my.log  | less -rp error`             #0.3 seconds

Keep up the good work!

**Comment by cornet** [comment]
Best filing an issue here https://github.com/madhouse/ccze which is the upstream version :)
